# Generated by Django 2.2.5 on 2020-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
            ],
        ),
    ]
