# Generated by Django 2.2.5 on 2020-01-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelByCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('continent', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('y2000', models.IntegerField()),
                ('y2001', models.IntegerField()),
                ('y2002', models.IntegerField()),
                ('y2003', models.IntegerField()),
                ('y2004', models.IntegerField()),
                ('y2005', models.IntegerField()),
                ('y2006', models.IntegerField()),
                ('y2007', models.IntegerField()),
                ('y2008', models.IntegerField()),
                ('y2009', models.IntegerField()),
                ('y2010', models.IntegerField()),
                ('y2011', models.IntegerField()),
                ('y2012', models.IntegerField()),
                ('y2013', models.IntegerField()),
                ('y2014', models.IntegerField()),
                ('y2015', models.IntegerField()),
                ('y2016', models.IntegerField()),
                ('y2017', models.IntegerField()),
                ('y2018', models.IntegerField()),
                ('y2019', models.IntegerField()),
            ],
        ),
    ]
