# Generated by Django 2.2.5 on 2020-01-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_travelbycountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentName',
            fields=[
                ('cont', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
            ],
        ),
    ]
