# Generated by Django 3.0.2 on 2020-01-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table1',
            new_name='Board1',
        ),
    ]
